# Generated by Django 5.2.11 on 2026-02-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bcp_tournament_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                (
                    "game_system",
                    models.CharField(default="Warhammer 40k", max_length=100),
                ),
                ("total_players", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-event_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArmyList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=150)),
                ("faction", models.CharField(max_length=120)),
                ("subfaction", models.CharField(blank=True, max_length=120)),
                ("placing", models.PositiveIntegerField(blank=True, null=True)),
                ("battle_points", models.FloatField(default=0)),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="army_lists",
                        to="analytics.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["placing", "player_name"],
            },
        ),
        migrations.CreateModel(
            name="UnitEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_name", models.CharField(max_length=150)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("points", models.PositiveIntegerField(default=0)),
                ("battlefield_role", models.CharField(blank=True, max_length=80)),
                (
                    "army_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="analytics.armylist",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_name"],
            },
        ),
        migrations.AddConstraint(
            model_name="armylist",
            constraint=models.UniqueConstraint(
                fields=("tournament", "player_name", "faction"),
                name="unique_player_faction_per_tournament",
            ),
        ),
    ]
